/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
    // VULNERABILITY 1: Hardcoded credentials
    private static final String DB_PASSWORD = "super_secret_password_123";
    private static final String DB_USER = "admin";
    private static final String DB_URL = "jdbc:mysql://localhost:3306/bank";
    public String getGreeting() {
        return "Hello from App 234!";
    }

    // VULNERABILITY 2: SQL Injection vulnerability
    public String getUserData(String username) {
        try {
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement stmt = conn.createStatement();
            // SQL Injection vulnerability - user input directly concatenated
            String query = "SELECT * FROM users WHERE username = '" + username + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            if (rs.next()) {
                return rs.getString("data");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // VULNERABILITY 3: Command Injection vulnerability
    public String executeCommand(String userInput) {
        try {
            // Command injection vulnerability - unsanitized user input
            Process process = Runtime.getRuntime().exec("ping " + userInput);
            return "Command executed";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "Error";
    }

    public static HttpServer createServer(int port) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/", new GreetingHandler());
        server.setExecutor(null); // use the default executor
        return server;
    }

    public static void main(String[] args) throws Exception {
        int port = args.length > 0 ? Integer.parseInt(args[0]) : 8080;
        HttpServer server = createServer(port);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> server.stop(0)));

        server.start();
        System.out.printf("Server running at http://localhost:%d/\n", port);

        // Keep the main thread alive so the server stays up until interrupted.
        Thread.currentThread().join();
    }

    private static class GreetingHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            byte[] response = new App().getGreeting().getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "text/plain; charset=utf-8");
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }
}
