/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
    // VULNERABILITY 1: Hardcoded credentials
    private static final String DB_PASSWORD = "super_secret_password_123";
    private static final String DB_USER = "admin";
    private static final String DB_URL = "jdbc:mysql://localhost:3306/bank";
    public String getGreeting() {
        return "Hello from App 234!";
    }

    // VULNERABILITY 2: SQL Injection vulnerability
    public String getUserData(String username) {
        try {
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement stmt = conn.createStatement();
            // SQL Injection vulnerability - user input directly concatenated
            String query = "SELECT * FROM users WHERE username = '" + username + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            if (rs.next()) {
                return rs.getString("data");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // VULNERABILITY 3: Command Injection vulnerability
    public String executeCommand(String userInput) {
        try {
            // Command injection vulnerability - unsanitized user input
            Process process = Runtime.getRuntime().exec("ping " + userInput);
            return "Command executed";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "Error";
    }

    public static HttpServer createServer(int port) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/", new GreetingHandler());
        server.createContext("/robots.txt", new RobotsHandler());
        server.createContext("/sitemap.xml", new SitemapHandler());
        server.createContext("/insecure", new InsecureHandler());
        server.createContext("/admin", new AdminHandler());
        server.createContext("/error", new ErrorDisclosureHandler());
        server.setExecutor(null); // use the default executor
        return server;
    }

    public static void main(String[] args) throws Exception {
        int port = args.length > 0 ? Integer.parseInt(args[0]) : 7070;
        HttpServer server = createServer(port);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> server.stop(0)));

        server.start();
        System.out.printf("Server running at http://localhost:%d/\n", port);

        // Keep the main thread alive so the server stays up until interrupted.
        Thread.currentThread().join();
    }

    // Utility method to add security headers to all responses
    private static void addSecurityHeaders(HttpExchange exchange) {
        exchange.getResponseHeaders().set("X-Content-Type-Options", "nosniff");
        exchange.getResponseHeaders().set("X-Frame-Options", "DENY");
        exchange.getResponseHeaders().set("X-XSS-Protection", "1; mode=block");
        exchange.getResponseHeaders().set("Strict-Transport-Security", "max-age=31536000; includeSubDomains");
        exchange.getResponseHeaders().set("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'");
        exchange.getResponseHeaders().set("Cross-Origin-Opener-Policy", "same-origin");
        exchange.getResponseHeaders().set("Cross-Origin-Embedder-Policy", "require-corp");
        // Cache headers will be set per-endpoint to avoid 'Non-Storable Content' warnings on static files
    }

    private static class GreetingHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            byte[] response = new App().getGreeting().getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "text/plain; charset=utf-8");
            // Dynamic content should not be cached
            exchange.getResponseHeaders().set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
            exchange.getResponseHeaders().set("Pragma", "no-cache");
            exchange.getResponseHeaders().set("Expires", "0");
            addSecurityHeaders(exchange);
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }

    // VULNERABILITY: Insecure endpoint with NO security headers, reflected XSS, and no input validation
    private static class InsecureHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            // Get query parameter without any validation or sanitization
            String query = exchange.getRequestURI().getQuery();
            String userName = "Guest";
            
            if (query != null && query.contains("name=")) {
                // Extract name parameter without sanitization - XSS vulnerability
                userName = query.substring(query.indexOf("name=") + 5);
                if (userName.contains("&")) {
                    userName = userName.substring(0, userName.indexOf("&"));
                }
            }
            
            // NO SECURITY HEADERS - ZAP will flag these issues:
            // - Missing X-Frame-Options (clickjacking protection)
            // - Missing X-Content-Type-Options (MIME sniffing protection)
            // - Missing Content-Security-Policy
            // - Missing X-XSS-Protection
            // - Missing Strict-Transport-Security (HSTS)
            
            // Reflected XSS vulnerability - user input directly in HTML response
            String htmlResponse = "<!DOCTYPE html><html><head><title>Insecure Page</title></head>" +
                    "<body>" +
                    "<h1>Welcome " + userName + "!</h1>" +  // User input reflected without encoding
                    "<p>This page has no security configuration.</p>" +
                    "<form>" +
                    "<input type='text' name='name' placeholder='Enter your name'>" +
                    "<button type='submit'>Submit</button>" +
                    "</form>" +
                    "</body></html>";
            
            byte[] response = htmlResponse.getBytes(StandardCharsets.UTF_8);
            
            // Add security headers to prevent XSS and other attacks
            exchange.getResponseHeaders().set("Content-Type", "text/html; charset=utf-8");
            // Dynamic page, do not cache
            exchange.getResponseHeaders().set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
            exchange.getResponseHeaders().set("Pragma", "no-cache");
            exchange.getResponseHeaders().set("Expires", "0");
            addSecurityHeaders(exchange);
            
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }

    // VULNERABILITY: Cookie Poisoning - Insecure session management
    // The application trusts client-side cookie values without cryptographic signing or server-side validation
    private static class AdminHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            // Get cookies from request
            String cookieHeader = exchange.getRequestHeaders().getFirst("Cookie");
            String userRole = "member"; // default role
            
            // Parse cookie to get user role
            if (cookieHeader != null && cookieHeader.contains("user=")) {
                int start = cookieHeader.indexOf("user=") + 5;
                int end = cookieHeader.indexOf(";", start);
                if (end == -1) end = cookieHeader.length();
                userRole = cookieHeader.substring(start, end);
            }
            
            String htmlResponse;
            
            // VULNERABILITY: Trusting client-side cookie without validation
            // Attacker can change cookie from user=member to user=admin
            if ("admin".equals(userRole)) {
                htmlResponse = "<!DOCTYPE html><html><head><title>Admin Panel</title></head>" +
                        "<body>" +
                        "<h1>🔓 You are the admin!</h1>" +
                        "<p>Welcome to the admin panel. You have full access.</p>" +
                        "<p>Current cookie: user=" + userRole + "</p>" +
                        "</body></html>";
            } else {
                htmlResponse = "<!DOCTYPE html><html><head><title>Access Denied</title></head>" +
                        "<body>" +
                        "<h1>❌ Access Denied</h1>" +
                        "<p>You are not authorized to access this page.</p>" +
                        "<p>Current cookie: user=" + userRole + "</p>" +
                        "<p>Only admins can access this page.</p>" +
                        "</body></html>";
            }
            
            byte[] response = htmlResponse.getBytes(StandardCharsets.UTF_8);
            
            // Set default cookie if not present
            if (cookieHeader == null || !cookieHeader.contains("user=")) {
                exchange.getResponseHeaders().set("Set-Cookie", "user=member; Path=/; HttpOnly; SameSite=Strict");
            }
            
            exchange.getResponseHeaders().set("Content-Type", "text/html; charset=utf-8");
            // Sensitive admin page, do not cache
            exchange.getResponseHeaders().set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
            exchange.getResponseHeaders().set("Pragma", "no-cache");
            exchange.getResponseHeaders().set("Expires", "0");
            addSecurityHeaders(exchange);
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }

    // VULNERABILITY 4: Application Error Disclosure
    // Exposes detailed error messages, stack traces, and internal application details
    // This allows attackers to gather information about the application's technology stack,
    // file paths, and internal workings, which can be used to craft targeted attacks
    private static class ErrorDisclosureHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String query = exchange.getRequestURI().getQuery();
            String errorType = "generic";
            
            if (query != null && query.contains("type=")) {
                errorType = query.substring(query.indexOf("type=") + 5);
                if (errorType.contains("&")) {
                    errorType = errorType.substring(0, errorType.indexOf("&"));
                }
            }
            
            String errorResponse = generateError(errorType);
            byte[] response = errorResponse.getBytes(StandardCharsets.UTF_8);
            
            // Return error details with 500 status code
            exchange.getResponseHeaders().set("Content-Type", "text/html; charset=utf-8");
            // Error responses should not be cached
            exchange.getResponseHeaders().set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
            exchange.getResponseHeaders().set("Pragma", "no-cache");
            exchange.getResponseHeaders().set("Expires", "0");
            addSecurityHeaders(exchange);
            exchange.sendResponseHeaders(500, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
        
        private String generateError(String errorType) {
            StringBuilder errorHtml = new StringBuilder();
            errorHtml.append("<!DOCTYPE html><html><head><title>Application Error</title>");
            errorHtml.append("<style>body{font-family:monospace;background:#f8d7da;padding:20px;}");
            errorHtml.append(".error-box{background:#fff;border:2px solid #721c24;padding:20px;margin:10px;}</style>");
            errorHtml.append("</head><body>");
            errorHtml.append("<h1>⚠️ Application Error</h1>");
            errorHtml.append("<div class='error-box'>");
            
            try {
                switch (errorType) {
                    case "database":
                        // Trigger a database error and expose the stack trace
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nonexistent", "admin", DB_PASSWORD);
                        break;
                    case "nullpointer":
                        // Trigger a NullPointerException
                        String nullString = null;
                        nullString.length();
                        break;
                    case "arrayindex":
                        // Trigger an ArrayIndexOutOfBoundsException
                        int[] array = new int[5];
                        int value = array[10];
                        break;
                    case "divide":
                        // Trigger an ArithmeticException
                        int result = 10 / 0;
                        break;
                    default:
                        // Generic error with full stack trace
                        throw new RuntimeException("Simulated application error for testing purposes");
                }
            } catch (Exception e) {
                // VULNERABILITY: Exposing detailed error information
                errorHtml.append("<h2>Error Type: ").append(e.getClass().getName()).append("</h2>");
                errorHtml.append("<h3>Error Message:</h3>");
                errorHtml.append("<p><strong>").append(e.getMessage()).append("</strong></p>");
                
                // Expose full stack trace - major security issue
                errorHtml.append("<h3>Stack Trace:</h3>");
                errorHtml.append("<pre style='background:#f5f5f5;padding:10px;overflow:auto;'>");
                for (StackTraceElement element : e.getStackTrace()) {
                    errorHtml.append("at ").append(element.toString()).append("\n");
                }
                errorHtml.append("</pre>");
                
                // Expose system information
                errorHtml.append("<h3>System Information:</h3>");
                errorHtml.append("<ul>");
                errorHtml.append("<li><strong>Java Version:</strong> ").append(System.getProperty("java.version")).append("</li>");
                errorHtml.append("<li><strong>Java Vendor:</strong> ").append(System.getProperty("java.vendor")).append("</li>");
                errorHtml.append("<li><strong>OS Name:</strong> ").append(System.getProperty("os.name")).append("</li>");
                errorHtml.append("<li><strong>OS Version:</strong> ").append(System.getProperty("os.version")).append("</li>");
                errorHtml.append("<li><strong>User Home:</strong> ").append(System.getProperty("user.home")).append("</li>");
                errorHtml.append("<li><strong>User Dir:</strong> ").append(System.getProperty("user.dir")).append("</li>");
                errorHtml.append("</ul>");
                
                // Expose application internals
                if (e.getCause() != null) {
                    errorHtml.append("<h3>Caused By:</h3>");
                    errorHtml.append("<p>").append(e.getCause().toString()).append("</p>");
                }
            }
            
            errorHtml.append("</div>");
            errorHtml.append("<div class='error-box'>");
            errorHtml.append("<h3>Test Different Error Types:</h3>");
            errorHtml.append("<ul>");
            errorHtml.append("<li><a href='/error?type=database'>Database Connection Error</a></li>");
            errorHtml.append("<li><a href='/error?type=nullpointer'>Null Pointer Exception</a></li>");
            errorHtml.append("<li><a href='/error?type=arrayindex'>Array Index Out of Bounds</a></li>");
            errorHtml.append("<li><a href='/error?type=divide'>Arithmetic Exception (Division by Zero)</a></li>");
            errorHtml.append("<li><a href='/error?type=generic'>Generic Runtime Exception</a></li>");
            errorHtml.append("</ul>");
            errorHtml.append("</div>");
            errorHtml.append("</body></html>");
            
            return errorHtml.toString();
        }
    }
    // Handler for robots.txt
    private static class RobotsHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String robotsContent = "User-agent: *\n" +
                    "Allow: /\n" +
                    "Disallow: /admin\n" +
                    "Disallow: /error\n" +
                    "Disallow: /insecure\n" +
                    "\n" +
                    "Sitemap: http://localhost:7070/sitemap.xml\n";
            
            byte[] response = robotsContent.getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "text/plain; charset=utf-8");
            // Static asset: safe to cache for a day
            exchange.getResponseHeaders().set("Cache-Control", "public, max-age=86400, immutable");
            addSecurityHeaders(exchange);
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }

    // Handler for sitemap.xml
    private static class SitemapHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String sitemapContent = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                    "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n" +
                    "  <url>\n" +
                    "    <loc>http://localhost:7070/</loc>\n" +
                    "    <lastmod>2026-01-27</lastmod>\n" +
                    "    <changefreq>daily</changefreq>\n" +
                    "    <priority>1.0</priority>\n" +
                    "  </url>\n" +
                    "  <url>\n" +
                    "    <loc>http://localhost:7070/insecure</loc>\n" +
                    "    <lastmod>2026-01-27</lastmod>\n" +
                    "    <changefreq>weekly</changefreq>\n" +
                    "    <priority>0.5</priority>\n" +
                    "  </url>\n" +
                    "</urlset>";
            
            byte[] response = sitemapContent.getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "application/xml; charset=utf-8");
            // Static asset: cache for an hour to allow updates
            exchange.getResponseHeaders().set("Cache-Control", "public, max-age=3600");
            addSecurityHeaders(exchange);
            exchange.sendResponseHeaders(200, response.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response);
            }
        }
    }
}
