/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    
    // Deprecated libraries with known vulnerabilities for SCA testing
    implementation("log4j:log4j:1.2.17")
    implementation("commons-collections:commons-collections:3.2.1")
    implementation("org.apache.struts:struts2-core:2.3.15.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.9.8")
    implementation("org.yaml:snakeyaml:1.18")
    implementation("com.thoughtworks.xstream:xstream:1.4.9")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.example.App"
        )
    }
}
