/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpServer;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test
    public void rootEndpointReturnsGreeting() throws Exception {
        HttpServer server = App.createServer(0);
        server.start();

        try {
            int port = server.getAddress().getPort();
            HttpURLConnection connection = (HttpURLConnection) new URL("http://localhost:" + port + "/").openConnection();
            connection.connect();

            String body;
            try (InputStream in = connection.getInputStream()) {
                body = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            }

            assertEquals(200, connection.getResponseCode());
            assertEquals(new App().getGreeting(), body);
        } finally {
            server.stop(0);
        }
    }
}
